### ISSUE TITLE
Consider dropping `DataFrames.jl` dependency

### ISSUE THREAD

**Issue by Moelf** [micahjsmith/BlsData.jl#5]
Just like `CSV.jl` doesn't depend on DataFrames.jl. A few reasons:
1. It's a huge dependency
2. which means that BlsData can hold back user's DataFrame in case of not updating frequently (there's nothing to be updated here since Bls API doesn't change that often)
3. you only need Tables interface and users can easily use DataFrame or whatever Table package if they want to

**Comment by micahjsmith** [comment]
Thanks for chiming in.

The contract of `BlsSeries` is that the returned data is a DataFrame. How would it be possible to return this data structure to the caller without depending on DataFrames.jl?

**Comment by Moelf** [comment]
why does it need to return a DataFrame?

If that's the case, then indeed you need to depend on DataFrames.jl, but it shouldn't? you can return a `Dict` or alike without losing generality...

**Comment by micahjsmith** [comment]
Most users of BlsData.jl (and similar FredData.jl) prefer to work directly with DataFrames. They are thus happy to receive DataFrames directly from the `get_data` calls without additional postprocessing.

What is your use case where DataFrames is a burdensome dependency?

Can you also clarify what you mean by 
> BlsData can hold back user's DataFrame in case of not updating frequently

There are no compatibility constraints from BlsData on DataFrames. You should be able to update to any version of DataFrames, no? If you are having issues with new versions of DataFrames, please create a new issue.

**Comment by Moelf** [comment]
>Most users of BlsData.jl (and similar FredData.jl) prefer to work directly with DataFrames. 

I don't doubt it, but it's trivial to go from one to the other (just put into a DataFrame), and not trivial to come back: imagine CSV.jl returns a DataFrame by default, now you want to work with so many CSV files that they don't fit in RAM at the same time, or you want to put them into a TypedTable for fast row iteration, you need to
